const KEY_POWER = 'KEY_POWER'
const KEY_MUTE = 'KEY_MUTE'
const KEY_VOLUP = 'KEY_VOLUP'
const KEY_VOLDOWN = 'KEY_VOLDOWN'
const KEY_CHDOWN = 'KEY_CHDOWN'
const KEY_CHUP = 'KEY_CHUP'

module.exports = {
  KEY_POWER,
  KEY_MUTE,
  KEY_VOLUP,
  KEY_VOLDOWN,
  KEY_CHUP,
  KEY_CHDOWN
}
